FROM python:3.11-slim

# Install dependencies
RUN apt-get update && apt-get install -y podman

# Copy app files
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY app.py .

# Expose Streamlit port
EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.runOnSave=true","--server.fileWatcherType=poll","--browser.gatherUsageStats=false", "--client.toolbarMode=minimal"]